### ISSUE TITLE
sir after generating text file what are the steps we have to do for training yolo v2 ?/

### ISSUE THREAD

**Issue by INNFINITEMINDS** [drainingsun/boobs#1]

**Comment by drainingsun** [comment]
There's a very good tutorial on that: https://timebutt.github.io/static/how-to-train-yolov2-to-detect-custom-objects/ Also good info at https://github.com/AlexeyAB/darknet Should be enough information to start :)

**Comment by INNFINITEMINDS** [comment]
RESPECTED SIR ,
I HAVE IMPLEMENTED YOLO TENSORFLOW VERSION DARKFLOW
NOW AFTER GENERATING TEXT FILE HOW CAN I CONVERT INTO DARKFLOW SUPPORTED FILE  ?
HELP REQUIRED !!
