### ISSUE TITLE
A more detailed manual

### ISSUE THREAD

**Issue by evilboss** [drainingsun/boobs#4]
Might consider adding a more detailed description on how to use the app

**Comment by drainingsun** [comment]
What exactly do you mean? It's a tool to makes boxes. It's pretty self explanatory and provides you necessary data to use with YOLO. If you are looking for info on HOW to use YOLO, there are plenty of guides online. I even linked one in my article about boobs: https://medium.com/@drainingsun/boobs-yolo-bbox-annotation-tool-96fb765d0036
