### ISSUE TITLE
Unsure if VOC XML annotations are correctly handled for multiple objects of the same class

### ISSUE THREAD

**Issue by keanedawg** [drainingsun/boobs#6]
Hey there, I want to thank you for making this. 

I annotated a set of images using boobs. My images include multiple appearances of the same object (in my case cars).

Here is a BOOBS-generated VOC file:

```
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>2656</xmin>
   <ymin>607</ymin>
   <xmax>3530</xmax>
   <ymax>1879</ymax>
   </bndbox>
   <bndbox>
   <xmin>1655</xmin>
   <ymin>939</ymin>
   <xmax>2451</xmax>
   <ymax>2106</ymax>
   </bndbox>
   <bndbox>
   <xmin>665</xmin>
   <ymin>1188</ymin>
   <xmax>1506</xmax>
   <ymax>2422</ymax>
   </bndbox>
</object>
```

So each object gets it's own bndbox.

Is this the right VOC annoation? I thought that each object should be wrapped in it's own "object" tag. For example:

```
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>2656</xmin>
   <ymin>607</ymin>
   <xmax>3530</xmax>
   <ymax>1879</ymax>
   </bndbox>
</object>
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>1655</xmin>
   <ymin>939</ymin>
   <xmax>2451</xmax>
   <ymax>2106</ymax>
   </bndbox>
</object>
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>665</xmin>
   <ymin>1188</ymin>
   <xmax>1506</xmax>
   <ymax>2422</ymax>
</bndbox>
</object>
</annotation>`
```

**Comment by drainingsun** [comment]
Can anyone confirm the exact specs for VOC. If this is true, I can fix this.

**Comment by m3rolam** [comment]
The spec should be that if you have the same object annotated multiple times in the same image, the `<object>` tag should be repeated for each annotation.

So the correct annotation should be:

<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>2656</xmin>
   <ymin>607</ymin>
   <xmax>3530</xmax>
   <ymax>1879</ymax>
   </bndbox>
</object>
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>1655</xmin>
   <ymin>939</ymin>
   <xmax>2451</xmax>
   <ymax>2106</ymax>
   </bndbox>
</object>
<object>
   <name>car</name>
   <pose>Unspecified</pose>
   <truncated>0</truncated>
   <occluded>0</occluded>
   <difficult>0</difficult>
   <bndbox>
   <xmin>665</xmin>
   <ymin>1188</ymin>
   <xmax>1506</xmax>
   <ymax>2422</ymax>
</bndbox>
</object>

So this mean that the current implementation is incorrect. This causes the website to produce incorrect annotations and also unsuccessfully import VOC annotations.

**Comment by drainingsun** [comment]
@m3rolam thanks! Will look into this ASAP.

**Comment by drainingsun** [comment]
Ok, so I think I resolved the problem. Closing the issue, but feel free to comment or open a new one if it's still not correct.
