### ISSUE TITLE
Images are rotated and annotations are saved as rotations

### ISSUE THREAD

**Issue by keanedawg** [drainingsun/boobs#8]
I'm capturing data and annotating it . Here is an example image

![image](https://user-images.githubusercontent.com/14279577/49613157-248bfd00-f964-11e8-83fd-bad390c9da47.png)

However, when I actually upload it in the tool:
![image](https://user-images.githubusercontent.com/14279577/49613341-9cf2be00-f964-11e8-979d-5bf039d9a208.png)

The image is rotated 90 degrees. The problem is that this causes the actual annotations to be incorrect unless I now manually rotate the image as well. Is there a way I can rotate the image inside of boobs (or not have it rotate at all?). Alternatively, the annotations could just be rotated as well. Thanks!

**Comment by keanedawg** [comment]
Note that these images were collected from a phone

**Comment by drainingsun** [comment]
Can you provide me with the original image that's being rotated? Also what OS and browser are you using? Does that happen to all images? I strongly suspect it's related to image meta data. If I have a sample, I could try finding a solution to this.

**Comment by keanedawg** [comment]
Hey @drainingsun, thanks for the response

I found the problem and [it is definitely related to the fact that it's taken from the phone](https://stackoverflow.com/questions/42702864/images-are-being-rotated-by-default-upon-upload/42707685#42707685). I think there is a tag called `exif` that corrects the phones angle depending on the orientation it was taken from. Some browsers ignore this tag though hence why the angle is different when viewed from the phone versus from a browser. I ended up fixing the problem using ImageMagick to convert all my images in a directory as [shown here](https://stackoverflow.com/questions/27778870/imagemagick-convert-to-keep-same-name-for-converted-image/27784462#27784462)

I am on Windows and Chrome. It happens to all images because they were all taken from my phone.

I am happy to send you an image with the problem. However, I'm not sure what the standard way of attaching files is on Github.

 Also, I am fine closing this issue

**Comment by drainingsun** [comment]
After a brief research it seems that browsers do not handle exif data properly and in general there is no consensus how it should be handled. There are solutions, though. Questions is, whether it is necessary. Personally I'd like to close this issue and re-investigate if more people encounter same issue.
