### ISSUE TITLE
I can't bounding box

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [drainingsun/boobs#9]
When I use your tool. But I turn on boobs.html. I can't Bounding box . I don't know why 

I have F12 but no error ???

You can fix this problem for me ???

Thanks you for contributing and reading

**Comment by drainingsun** [comment]
Hi,

You will have to be more specific than that. Post screenshots, browser/os versions, exact actions performed.

Thanks

**Comment by NguyenThaiHoc1** [comment]
SOrry ! I did it. thanks you for attention my question
